import "@cloudscape-design/global-styles/index.css";
import { type Metadata } from "next";
import { CloudscapeLayout } from "~/app/_components/cloudscape-layout";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>
          <CloudscapeLayout>{children}</CloudscapeLayout>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
